# This GitHub workflow will build the documentation and publish it on GitHub Pages.
#
# How to start using this workflow:
# * Create, push and merge a PR with these changes:
#   - Put this file into /.github/workflows/
#   - Create an empty file /.nojekyll
#   - Create a file /.gh-pages-exclude with the following content:
#       # rsync exclude patterns for the documentation build. For details on the syntax,
#       # see https://linuxize.com/post/how-to-exclude-files-and-directories-with-rsync/
#       # or https://download.samba.org/pub/rsync/rsync.html.
#       # Path names are relative to the 'docs_build' directory.
#       .doctrees
#   - Update the docs badge in the README .rst file as follows:
#       .. image:: https://github.com/{org}/{repo}/workflows/docs/badge.svg?branch=master
#           :target: https://github.com/{org}/{repo}/actions?query=workflow%3Adocs
#           :alt: Docs build status (master)
# * Create and push a branch gh-pages (without a PR):
#   git checkout master
#   git checkout -b gh-pages
#   git push --set-upstream origin gh-pages
# * This should automatically set gh-pages as the branch to build from on settings/pages

name: docs

env:

  # Command that builds the documentation
  doc_build_cmd: make builddoc

  # Directory where the documentation is built in main worktree
  doc_build_dir: build_doc

  # Branch that is checked out for building the docs.
  # We always build from master even when a stable branch has triggered the
  # workflow, in order to pick up the conf.py file consistently, independent of
  # the triggering branch. The built documentation will contain versions for the
  # list of tags and branches defined in conf.py, so these versions and also
  # any other build parameters will be consistent that way.
  doc_branch: master

on:
  push:
    # PR merge to these branches triggers this workflow
    branches: [ master, stable_0.5 ]

jobs:

  docs:
    runs-on: macos-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # TODO: Understand if this is needed
        fetch-depth: 0  # Required for pushing to the repo
        ref: ${{ env.doc_branch }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up development environment
      run: |
        make develop

    - name: Build documentation
      run: |
        ${{ env.doc_build_cmd }}

    - name: Set up gh-pages worktree
      run: |
         git worktree add gh-pages gh-pages
         bash -c "cd gh-pages; git fetch"

    - name: Sync documentation to gh-pages worktree
      # The file .gh-pages-exclude defines files to be excluded from the sync
      run: |
         rm -rf gh-pages/*
         rm -rf gh-pages/.doctrees
         rm -f gh-pages/.buildinfo
         ls -al gh-pages
         rsync -a --exclude-from=.gh-pages-exclude ${{ env.doc_build_dir }}/ gh-pages/

    - name: Commit changes in the gh-pages branch locally
      # The git config can specify any user name and email
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        bash -c "cd gh-pages; git add .; git status; git commit -m 'Docs update from PR with commit ${{ github.SHA }}'; true"

    - name: Push gh-pages branch to upstream repo
      uses: ad-m/github-push-action@master
      # From https://github.com/marketplace/actions/github-push
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        directory: gh-pages
        force: true
